-- MySQL Script generated by MySQL Workbench
-- Wed Dec 11 10:21:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'; */

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ;
USE [mydb] ;

-- -----------------------------------------------------
-- Table `mydb`.`Facultad`
-- -----------------------------------------------------
CREATE TABLE mydb.Facultad (
  [idFacultad] INT NOT NULL,
  [Nombre] VARCHAR(45) NOT NULL,
  [Clave] VARCHAR(45) NOT NULL,
  PRIMARY KEY ([idFacultad]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Academico`
-- -----------------------------------------------------
CREATE TABLE mydb.Academico (
  [idAcademico] INT NOT NULL IDENTITY,
  [idFacultad] INT NOT NULL,
  [NoControl] VARCHAR(10) NOT NULL,
  [rfc] VARCHAR(45) NULL,
  PRIMARY KEY ([idAcademico]),
  CONSTRAINT [NoControl_UNIQUE] UNIQUE  ([NoControl] ASC) VISIBLE,
  INDEX `facultad_idx` ([idFacultad] ASC) VISIBLE,
  CONSTRAINT [facultad]
    FOREIGN KEY ([idFacultad])
    REFERENCES `mydb`.`Facultad` ([idFacultad])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Academia`
-- -----------------------------------------------------
CREATE TABLE mydb.Academia (
  [idAcademia] INT NOT NULL IDENTITY,
  [nombre] VARCHAR(45) NOT NULL,
  PRIMARY KEY ([idAcademia]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Academico_academia`
-- -----------------------------------------------------
CREATE TABLE mydb.Academico_academia (
  [idacademico_academia] INT NOT NULL IDENTITY,
  [id_academico] INT NOT NULL,
  [id_academia] INT NOT NULL,
  PRIMARY KEY ([idacademico_academia])
  CREATE INDEX [id_academico_idx] ON mydb.Academico_academia ([id_academico] ASC) VISIBLE,
  INDEX `Academia_Academico_academia_idx` ([id_academia] ASC) VISIBLE,
  CONSTRAINT [Academico_Academico_academia]
    FOREIGN KEY ([id_academico])
    REFERENCES `mydb`.`Academico` ([idAcademico])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [Academia_Academico_academia]
    FOREIGN KEY ([id_academia])
    REFERENCES `mydb`.`Academia` ([idAcademia])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE mydb.Evento (
  [idEvento] INT NOT NULL IDENTITY,
  [nombre_evento] VARCHAR(45) NOT NULL,
  [fecha_evento] DATETIME2(0) NOT NULL,
  [descripcion_evento] VARCHAR(45) NOT NULL,
  [FechaFin] DATE NOT NULL,
  [HoraInicio] DATE NOT NULL,
  PRIMARY KEY ([idEvento]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Sede_Evento`
-- -----------------------------------------------------
CREATE TABLE mydb.Sede_Evento (
  [idSede_Evento] INT NOT NULL IDENTITY,
  [nombre_sede_evento] VARCHAR(45) NOT NULL,
  [descripcion_sede_evento] VARCHAR(45) NULL,
  PRIMARY KEY ([idSede_Evento]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Evento_Sede_Evento`
-- -----------------------------------------------------
CREATE TABLE mydb.Evento_Sede_Evento (
  [idEvento_Sede_Evento] INT NOT NULL IDENTITY,
  [id_evento] INT NOT NULL,
  [id_Sede_Evento] INT NULL,
  PRIMARY KEY ([idEvento_Sede_Evento])
  CREATE INDEX [Sede_Evento_Evento_Sede_Evento_idx] ON mydb.Evento_Sede_Evento ([id_Sede_Evento] ASC) VISIBLE,
  INDEX `Evento_Evento_Sede_Evento_idx` ([id_evento] ASC) VISIBLE,
  CONSTRAINT [Sede_Evento_Evento_Sede_Evento]
    FOREIGN KEY ([id_Sede_Evento])
    REFERENCES `mydb`.`Sede_Evento` ([idSede_Evento])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [Evento_Evento_Sede_Evento]
    FOREIGN KEY ([id_evento])
    REFERENCES `mydb`.`Evento` ([idEvento])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Academico_Evento`
-- -----------------------------------------------------
CREATE TABLE mydb.Academico_Evento (
  [idAcademico_Evento] INT NOT NULL IDENTITY,
  [id_Academico] INT NOT NULL,
  [id_Evento] INT NOT NULL,
  PRIMARY KEY ([idAcademico_Evento])
  CREATE INDEX [Academico_Academico_Evento_idx] ON mydb.Academico_Evento ([id_Academico] ASC) VISIBLE,
  INDEX `Evento_Academico_Evento_idx` ([id_Evento] ASC) VISIBLE,
  CONSTRAINT [Academico_Academico_Evento]
    FOREIGN KEY ([id_Academico])
    REFERENCES `mydb`.`Academico` ([idAcademico])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [Evento_Academico_Evento]
    FOREIGN KEY ([id_Evento])
    REFERENCES `mydb`.`Evento` ([idEvento])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coordinacion`
-- -----------------------------------------------------
CREATE TABLE mydb.Coordinacion (
  [idCoordinacion] INT NOT NULL IDENTITY,
  [nombre] VARCHAR(45) NULL,
  PRIMARY KEY ([idCoordinacion]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Cuerpo_Academico`
-- -----------------------------------------------------
CREATE TABLE mydb.Cuerpo_Academico (
  [idCuerpo_Academico] INT NOT NULL IDENTITY,
  PRIMARY KEY ([idCuerpo_Academico]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Cuero_Colegial`
-- -----------------------------------------------------
CREATE TABLE mydb.Cuero_Colegial (
  [idCuero_Colegial] INT NOT NULL IDENTITY,
  PRIMARY KEY ([idCuero_Colegial]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE mydb.Roles (
  [idRol] INT NOT NULL,
  [Nombre] VARCHAR(45) NOT NULL,
  [Descripcion] VARCHAR(45) NOT NULL,
  PRIMARY KEY ([idRol]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE mydb.Permisos (
  [idPermiso] INT NOT NULL,
  [Clave] VARCHAR(40) NOT NULL,
  [Descripcion] VARCHAR(80) NOT NULL,
  PRIMARY KEY ([idPermiso]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Roles_Permisos`
-- -----------------------------------------------------
CREATE TABLE mydb.Roles_Permisos (
  [idRolPermiso] INT NOT NULL,
  [idRol] INT NOT NULL,
  [idPermiso] INT NOT NULL,
  PRIMARY KEY ([idRolPermiso])
  CREATE INDEX [idRol_idx] ON mydb.Roles_Permisos ([idRol] ASC) VISIBLE,
  INDEX `idPermiso_idx` ([idPermiso] ASC) VISIBLE,
  UNIQUE INDEX `rolPermiso` ([idRol] ASC, [idPermiso] ASC) VISIBLE,
  CONSTRAINT [idRol]
    FOREIGN KEY ([idRol])
    REFERENCES `mydb`.`Roles` ([idRol])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [idPermiso]
    FOREIGN KEY ([idPermiso])
    REFERENCES `mydb`.`Permisos` ([idPermiso])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DatosPersonales`
-- -----------------------------------------------------
CREATE TABLE mydb.DatosPersonales (
  [idDatosPersonales] INT NOT NULL,
  [Nombre] VARCHAR(45) NOT NULL,
  [ApellidoPaterno] VARCHAR(45) NOT NULL,
  [ApellidoMaterno] VARCHAR(45) NOT NULL,
  [FechaNacimiento] DATE NOT NULL,
  [Created] DATETIME2(0) NOT NULL DEFAULT GETDATE(),
  [Updated] DATETIME2(0) NOT NULL DEFAULT GETDATE(),
  [Deleted] DATETIME2(0) NOT NULL,
  [CreatedBy] INT NOT NULL,
  [UpdatedBy] INT NOT NULL,
  PRIMARY KEY ([idDatosPersonales])
  CREATE INDEX [createdBy_idx] ON mydb.DatosPersonales ([CreatedBy] ASC) VISIBLE,
  INDEX `UpdatedBy_idx` ([UpdatedBy] ASC) VISIBLE,
  CONSTRAINT [createdBy]
    FOREIGN KEY ([CreatedBy])
    REFERENCES `mydb`.`Usuario` ([idUsuario])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [UpdatedBy]
    FOREIGN KEY ([UpdatedBy])
    REFERENCES `mydb`.`Usuario` ([idUsuario])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE mydb.Estudiante (
  [idEstudiante] INT NOT NULL IDENTITY,
  [idUsuario] INT NOT NULL,
  [Matricula] VARCHAR(10) NOT NULL,
  PRIMARY KEY ([idEstudiante]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE mydb.Usuario (
  [idUsuario] INT NOT NULL,
  [idDatosPersonales] INT NOT NULL IDENTITY,
  [idAcademico] INT NULL,
  [idEstudiante] INT NULL,
  [email] VARCHAR(45) NOT NULL,
  [password] VARCHAR(45) NOT NULL,
  PRIMARY KEY ([idUsuario])
  CREATE INDEX [datosPersonales_idx] ON mydb.Usuario ([idDatosPersonales] ASC) VISIBLE,
  INDEX `estudiante_idx` ([idEstudiante] ASC) VISIBLE,
  INDEX `academico_idx` ([idAcademico] ASC) VISIBLE,
  CONSTRAINT [datosPersonales]
    FOREIGN KEY ([idDatosPersonales])
    REFERENCES `mydb`.`DatosPersonales` ([idDatosPersonales])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [estudiante]
    FOREIGN KEY ([idEstudiante])
    REFERENCES `mydb`.`Estudiante` ([idEstudiante])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [academico]
    FOREIGN KEY ([idAcademico])
    REFERENCES `mydb`.`Academico` ([idAcademico])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol_Usuario`
-- -----------------------------------------------------
CREATE TABLE mydb.Rol_Usuario (
  [idRol_Usuario] INT NOT NULL,
  [idRol] INT NOT NULL,
  [idUsuario] INT NOT NULL,
  PRIMARY KEY ([idRol_Usuario])
  CREATE INDEX [rolUsuario_idx] ON mydb.Rol_Usuario ([idRol] ASC) VISIBLE,
  INDEX `usuario_idx` ([idUsuario] ASC) INVISIBLE,
  UNIQUE INDEX `llaveUnica` ([idRol] ASC, [idUsuario] ASC) VISIBLE,
  CONSTRAINT [rol]
    FOREIGN KEY ([idRol])
    REFERENCES `mydb`.`Roles` ([idRol])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [usuario]
    FOREIGN KEY ([idUsuario])
    REFERENCES `mydb`.`Usuario` ([idUsuario])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoOrganizador`
-- -----------------------------------------------------
CREATE TABLE mydb.tipoOrganizador (
  [idtipoOrganizador] INT NOT NULL,
  [Nombre] VARCHAR(55) NOT NULL,
  [Descripcion] VARCHAR(45) NOT NULL,
  PRIMARY KEY ([idtipoOrganizador]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Organizador`
-- -----------------------------------------------------
CREATE TABLE mydb.Organizador (
  [idOrganizador] INT NOT NULL,
  [idTipoOrganizador] INT NOT NULL,
  [idEvento] INT NOT NULL,
  [idAcademico] INT NOT NULL,
  PRIMARY KEY ([idOrganizador])
  CREATE INDEX [tipoOrganizador_idx] ON mydb.Organizador ([idTipoOrganizador] ASC) VISIBLE,
  INDEX `evento_idx` ([idEvento] ASC) VISIBLE,
  INDEX `academico_idx` ([idAcademico] ASC) VISIBLE,
  CONSTRAINT [tipoOrganizador]
    FOREIGN KEY ([idTipoOrganizador])
    REFERENCES `mydb`.`tipoOrganizador` ([idtipoOrganizador])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [evento]
    FOREIGN KEY ([idEvento])
    REFERENCES `mydb`.`Evento` ([idEvento])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [academico]
    FOREIGN KEY ([idAcademico])
    REFERENCES `mydb`.`Academico` ([idAcademico])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Documento`
-- -----------------------------------------------------
CREATE TABLE mydb.Documento (
  [idDocumento] INT NOT NULL,
  [nombre] VARCHAR(45) NOT NULL,
  [descripcion] VARCHAR(45) NULL,
  [tipo] VARCHAR(45) NOT NULL,
  [formato] VARCHAR(45) NOT NULL,
  PRIMARY KEY ([idDocumento]))
;


-- -----------------------------------------------------
-- Table `mydb`.`Evento_Documento`
-- -----------------------------------------------------
CREATE TABLE mydb.Evento_Documento (
  [idEvento_Documento] INT NOT NULL,
  [idDocumento] INT NOT NULL,
  [idEvento] INT NOT NULL
  CREATE INDEX [documento_idx] ON mydb.Evento_Documento ([idDocumento] ASC) VISIBLE,
  INDEX `evento_idx` ([idEvento] ASC) VISIBLE,
  CONSTRAINT [documento]
    FOREIGN KEY ([idDocumento])
    REFERENCES `mydb`.`Documento` ([idDocumento])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [evento]
    FOREIGN KEY ([idEvento])
    REFERENCES `mydb`.`Evento` ([idEvento])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */
